name: afetpay
description: "A new Flutter projectt."

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: ^3.5.0
  uuid: ^4.5.1

  cryptography: ^2.9.0
  cupertino_icons: ^1.0.8
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  geolocator: ^11.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
